name: infomosaic
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests=2.32.3
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - spacy=3.8.2
  - pyspark=3.5.3
  - beautifulsoup4=4.12.3
  - vaderSentiment=3.3.2
  - textblob=0.18.0.post0
  - libxml2
  - libxslt
  - pip
  - pip:
      - pybloom-live==4.0.0
      - deep-translator==1.11.4
      - spacy[lookups]