print("oi")

import os

# Define the output directory and file name
output_dir = "data/"
output_file = os.path.join(output_dir, "test_file.txt")

# Ensure the directory exists
os.makedirs(output_dir, exist_ok=True)

# Write some test data to the file
with open(output_file, "w") as file:
    file.write("This is a test file generated by the Python script.\n")
    file.write("Hello from inside the Docker container!\n")

print(f"File created at: {output_file}")